--IZGUBU SM ORIGINALNO KOPIJO MEGA JE PA DOL FUKNU LINK

--I LOST THE ORIGINAL COPY OF THIS SERVER AND MEGA TOOK DOWN THE LINK

game = "https://mega.nz/file/eNJDiKyA#UKSWfqUAKvE_HVBRFPNHepqmekokshkul2I6klJl8zQ"

print(game)
